### PR TITLE
Bump to latest tokio-util

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by benesch** [comment]
Welp, no good deed goes unpunished.

https://github.com/tokio-rs/tokio/pull/2326

**Comment by benesch** [comment]
Ok, this is ready to merge now thanks to tokio-util v0.3.1!

**Comment by LucioFranco** [comment]
Im still tired this morning but to make sure @seanmonstar this isn't a breaking change?

**Comment by seanmonstar** [comment]
I'm pretty sure it's only used internally, in `codec`.

**Pull request merged**
