### PR TITLE
Replace futures-util with atomic-waker and manual poll_fn

### LINKED ISSUE #507: Remove futures-util dependency
h2 currently depends on futures-util, which is rather heavy (containing heaps of combinators, plus pulling in most of the other futures-* crates) for only two things: `poll_fn` and `AtomicWaker`. `poll_fn` could trivially be copy-pasted (and is also [coming to std](https://github.com/rust-lang/rust/issues/72302) so eventually that could be used), but the same thing is not true for `AtomicWaker`. I am not really familiar with the details of wakers, so don't really know how feasible it is to replace that / whether there's maybe an equivalent in tokio / tokio-utils.

I hope there is some new info in this issue. If somebody knows about a good replacement for futures-util's `AtomicWaker`, I'd be happy to create a PR removing the futures-util dependency.

### PR DESCRIPTION
**Pull request by notgull**
This removes ones of the heavier dependencies. The goal is to also remove
futures-util from the rest of the dependency tree, which is hard to justify when
futures-util is used in more fundamental dependencies.

Closes #507 

Signed-off-by: John Nunley <dev@notgull.net>

### CODE REVIEW

**Comment by notgull** [comment]
@seanmonstar Any chance you can review this?

**Comment by seanmonstar** [comment]
Sorry, yes I will take a look, but I want to check out this separate dependency, and just didn't have time while trying to cram all the prep work to release hyper 1.0 (today).

**Review by GlenDC — APPROVED** [review]

**Review by jplatte — APPROVED** [review]

**Comment by notgull** [comment]
@seanmonstar Has `hyper` v1.0 craziness cooled off enough for you to have time to review this?

**Review by mladedav — APPROVED** [review]

**Review by dswij — APPROVED** [review]

**Comment by notgull** [comment]
@seanmonstar Just following up on this. Have you had to chance to consider this yet?

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
