### PR TITLE
Read body in the example server

### PR DESCRIPTION
**Pull request by kornelski**
Expands the example to demonstrate reading of the body.

### CODE REVIEW

**Comment by kornelski** [comment]
Is this code correct? 

```rust
       let body = request.body_mut();
        while let Some(data) = body.data().await {
            let data = data?;
            println!("<<<< recv {:?}", data);
        }
```

This loop gets stuck after receiving 65535 bytes.

```
GOT request: Request { method: POST, uri: http://127.0.0.1:5928/, version: HTTP/2.0, headers: {"user-agent": "curl/7.54.0", "accept": "*/*", "content-length": "100000", "content-type": "application/x-www-form-urlencoded"}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(1), ref_count: 2 } } } }
<<<< recv 16384 bytes
<<<< recv 16384 bytes
<<<< recv 16384 bytes
<<<< recv 16383 bytes
```

I'm testing with `curl`

```sh
yes | head -n 100000 > f
curl --http2-prior-knowledge http://127.0.0.1:5928  -d @f
```

**Comment by Tonyce** [comment]
also have the problem
截屏2021-03-12 下午8 20 10

**Comment by nox** [comment]
I tried this with `body.flow_control().release_capacity(data.len())` in the loop but that didn't help either.

**Comment by nox** [comment]
I am almost certain the issue is on curl's side.

**Comment by nox** [comment]
Hah, never mind, I managed to repro that with the client example connecting to the server example 😅

**Comment by nox** [comment]
Superseded by #544, turns out we were not driving the connection at all anymore.

**Comment by kornelski** [comment]
In any one is wondering why this didn't work — it needs a call to `poll_close` 

https://docs.rs/h2/0.3.3/h2/server/index.html#managing-the-connection

**Comment by nox** [comment]
Oh `poll_close` is supposed to be deprecated (in favour of `poll_closed`), I will update those docs.

**Pull request closed without merging**
